FROM rust:1.75 as builder
# build release binary
WORKDIR /usr/src/app

COPY . .
RUN cargo build --release

FROM ollama/ollama:0.3.11
COPY --from=builder /usr/src/app/target/release/dkn-compute /bin/dkn-compute

RUN apt-get update && \
    apt-get install -y supervisor && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/log/supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

ENV OLLAMA_PORT=11434
ENV OLLAMA_HOST=http://127.0.0.1
ENV OLLAMA_AUTO_PULL=true

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/start.sh"]
