name: Create Side Image
on:
  push:
    branches: ["side"]
    paths:
      # Source files in each member
      - "compute/src/**"
      - "p2p/src/**"
      - "workflows/src/**"
      # Cargo in each member
      - "compute/Cargo.toml"
      - "p2p/Cargo.toml"
      - "workflows/Cargo.toml"
      # root-level changes
      - "Cargo.lock"
      - "Cross.toml"
      - "Dockerfile"
      - "compose.yml"
      # workflow itself
      - ".github/workflows/build_side_container.yml"

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Unix Time
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Get SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get Branch Name
        id: branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Set Image Tag
        id: itag
        run: echo "itag=${{ steps.branch.outputs.branch }}-${{ steps.sha.outputs.sha }}-${{ steps.timestamp.outputs.timestamp }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ steps.itag.outputs.itag }}
        with:
          platforms: linux/amd64, linux/arm64, linux/arm, linux/arm64v8
          push: true
          tags: |
            firstbatch/dkn-compute-node:unstable
            firstbatch/dkn-compute-node:${{ env.IMAGE_TAG }}
